# Generated by Django 2.1.7 on 2020-01-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_auto_20200116_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
